import Head from 'next/head';
import { Container, Heading } from '@chakra-ui/react';
import { Example } from '../../../dist';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container as="main">
        <Heading>Solana Wallet Adapter Chakra UI</Heading>

        <Example />
      </Container>
    </>
  );
}
